language: ruby
rvm:
- 2.4.2
notifications:
  slack:
    secure: QuYXWOwIUNKgda6yABEGv/gZL6xD0Vg74WmfNM71N6w0IEhZaZD1uJxuxhqZ8ypwQywFLckYmMQxnZrbo+Iw5aPU+cz3b5YvmBdJqc2wJuwFi9F7b/1dBvMYOyU3WrhWDiCmIWrsNP38Rs0Adnq9/2tioCwMJEqEN6ZhtI8Ydih1dtwRpPO1tKcZDTfKXNDK9VWISOjEnv9yqoP/VJ6jQicmr+Hnvfhq3yttsTlgQkAUbkl9NzfRM1E5bALCFc3QgnDZAvAXW1ZoS17z6zr2cD0YHi+OB7LzAqocUkc4OINCFCle7W83JCLLwrhSbfFlarOKwvE+R4KWs0DAhF/zTTD9Pp1sNNZMgP8fp3mGUmFtZiyragWnFbamHuSxlwyQ27uUsXgWGhZbsAW2JLkGGBXOn4sDED+HM4l0b0oaKB05SudTEeRjfwAL9M8HLcDd0vzMpaIrZO3VXX1HKVEzgDYTq1ylVTe1dRmt2jwIlP1Xn8ySIqDFNF8+ZfBnH5F6Le6WpcZmkGYnjyPle7YDGVRsxmRedUsa5gHVnraR8vtE/R0xIwW5murGfJljvdCKrb2oDpKWw4YwSUxeLojQD1WCLjmhh5iObQjU6nz3IrX33xrlupX6WcUKNwoVV4/QNQoxesu3Rwt5krugVpUYVNxrOUaam7aH/UPbN+6RTbM=
